steps:
- label: ":white_check_mark: :python-black: Checks"
  command: nix flake check

- wait

- label: ":python: :pytest: Pytest"
  command: podman system service --time=0 unix:///var/run/docker.sock & nix develop --sandbox -c 'ci-test'

- wait

- label: ":python: :hammer: Poetry Build"
  command: nix develop --sandbox -c 'ci-build'

